import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';

// Initialize Supabase Service Client for test setup/teardown
// We use the service role key from env vars (assumed available in test env)
// If not available, we might fallback or skip (but for local verify we need it)
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

const supabase = createClient(supabaseUrl, serviceRoleKey);

const TEST_EMAIL = 'test@cinegrok.com';
const TEST_PASSWORD = 'TestPassword123!';

test.describe('Beta Publish Flow', () => {
    let testUserId: string;

    test.beforeAll(async () => {
        if (!serviceRoleKey) {
            console.warn('Skipping test setup: No SUPABASE_SERVICE_ROLE_KEY');
            return;
        }

        // 1. Get Test User ID
        const { data: { users }, error } = await supabase.auth.admin.listUsers();
        if (error) throw error;

        const user = users.find(u => u.email === TEST_EMAIL);
        if (!user) {
            // Create user if not exists (handling the auth setup gap)
            const { data: newUser, error: createError } = await supabase.auth.admin.createUser({
                email: TEST_EMAIL,
                password: TEST_PASSWORD,
                email_confirm: true
            });
            if (createError) throw createError;
            testUserId = newUser.user.id;
        } else {
            testUserId = user.id;
        }

        console.log(`Test User ID: ${testUserId}`);

        // 2. Reset Data: Delete existing subscription and filmmaker profile
        await supabase.from('subscriptions').delete().eq('user_id', testUserId);
        await supabase.from('filmmakers').delete().eq('user_id', testUserId);

        // 3. Inject Valid Draft
        const draftData = {
            stageName: "Beta Test Director",
            email: TEST_EMAIL,
            bio: "This is a test bio generated by Playwright.",
            primaryRoles: ["Director", "Writer"],
            country: "India",
            location: "Mumbai",
            experienceLevel: "Professional",
            website: "https://example.com"
        };

        const { error: draftError } = await supabase
            .from('profile_drafts')
            .upsert({
                user_id: testUserId,
                draft_data: draftData,
                updated_at: new Date().toISOString()
            });

        if (draftError) throw draftError;
        console.log('Test setup complete: User reset and draft injected.');
    });

    test('User can select plan, claim beta, and see published profile', async ({ page }) => {
        // 1. Login
        await page.goto('/auth/login');
        await page.getByLabel(/email/i).fill(TEST_EMAIL);
        await page.getByLabel(/password/i).fill(TEST_PASSWORD);
        await page.getByRole('button', { name: /log in|sign in|submit/i }).click();
        await expect(page).toHaveURL(/\/(dashboard|profile-builder)?/);

        // 2. Go to Plans Page (simulating redirect from Wizard)
        await page.goto('/plans?from=profile-builder');

        // 3. Verify Plans Page Loaded
        await expect(page.locator('h1')).toContainText('Choose Your Plan');
        await expect(page.locator('.beta-badge')).toBeVisible();

        // 4. Select Monthly Plan (should be selected by default, but verify)
        // Check for Free/Strike-through price
        await expect(page.locator('.plan-card.selected')).toBeVisible();
        await expect(page.locator('.plan-card.selected .beta-price')).toHaveText('FREE');

        // 5. Click Claim & Publish
        // Setup listener for console to catch logs
        page.on('console', msg => console.log(`BROWSER: ${msg.text()}`));

        await page.click('.claim-button');

        // 6. Verify Redirect to Profile Page
        // Wait for URL to change to /filmmakers/[uuid]
        await expect(page).toHaveURL(/\/filmmakers\/[0-9a-f-]{36}/, { timeout: 30000 });

        const profileUrl = page.url();
        console.log(`Redirected to profile: ${profileUrl}`);

        // 7. Verify Profile Page Content
        // It should NOT show 404
        await expect(page.locator('h1')).not.toContainText('Not Found');
        await expect(page.locator('h1')).not.toContainText('404');

        // It SHOULD show the stage name
        await expect(page.locator('body')).toContainText('Beta Test Director');
        await expect(page.locator('body')).toContainText('Director');

        console.log('Profile page verified successfully.');
    });
});
